#!/usr/bin/env python3
# version: 0.1.0
"""test_suggestion_parser_moc_branch.py — T4.1: MOC proposal-doc pre-parse dispatch.

Eight tests cover the new `parse_moc_proposal_doc` branch added to
`suggestion-parser.py`:

  test_dispatch_on_filename_pattern        — filename tomo-moc-proposal-*.md routes to MOC branch
  test_dispatch_on_frontmatter_type        — frontmatter type: tomo-proposal routes to MOC branch
  test_skip_when_only_some_clusters_accepted — multi-cluster doc, 1 of 3 accepted → len == 1
  test_no_clusters_accepted_returns_empty  — no Accept ticks → returns []
  test_parse_children_list_extracts_ticked_only — only [x] children extracted
  test_parse_parent_single_select_first_check_wins — multiple parent ticks, first wins
  test_parse_override_toggle_extracts_bool — override ticked → override_preserve_existing_up True
  test_editable_text_fields_extracted      — Title/Location/Template extracted

Fixtures are generated by importing `render_moc_proposal_doc` from
`suggestions-reducer.py` with a DiscoveryReport skeleton, following the
pattern in `tests/test_reducer_moc_proposal_mode.py` (per
feedback_fixture_from_live_render.md).
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

TESTS_DIR = Path(__file__).resolve().parent
REPO_ROOT = TESTS_DIR.parent
SCRIPTS_DIR = REPO_ROOT / "tomo" / "scripts"

# ── Load suggestion-parser.py as a module (hyphen → importlib) ─────────────

_PARSER_PATH = SCRIPTS_DIR / "suggestion-parser.py"
_parser_spec = importlib.util.spec_from_file_location("suggestion_parser", _PARSER_PATH)
_parser_mod = importlib.util.module_from_spec(_parser_spec)
assert _parser_spec.loader is not None
sys.modules["suggestion_parser"] = _parser_mod
_parser_spec.loader.exec_module(_parser_mod)

parse_moc_proposal_doc = _parser_mod.parse_moc_proposal_doc  # type: ignore[attr-defined]

# ── Load suggestions-reducer.py for live fixture generation ─────────────────

_REDUCER_PATH = SCRIPTS_DIR / "suggestions-reducer.py"
_reducer_spec = importlib.util.spec_from_file_location("suggestions_reducer", _REDUCER_PATH)
_reducer_mod = importlib.util.module_from_spec(_reducer_spec)
assert _reducer_spec.loader is not None
sys.modules["suggestions_reducer"] = _reducer_mod
_reducer_spec.loader.exec_module(_reducer_mod)

render_moc_proposal_doc = _reducer_mod.render_moc_proposal_doc  # type: ignore[attr-defined]


# ── Stub config ──────────────────────────────────────────────────────────────

class _Cfg:
    def __init__(self, max_results: int = 5):
        self.max_results = max_results


# ── Report builder helpers (mirrored from test_reducer_moc_proposal_mode.py) ─


def _candidate(
    stem: str,
    *,
    existing_up: str | None = None,
    existing_up_broken: bool = False,
    topics: list[str] | None = None,
    classification: str | None = None,
) -> dict:
    return {
        "stem": stem,
        "path": f"Atlas/202 Notes/{stem}.md",
        "topics": topics or [],
        "existing_up": existing_up,
        "existing_up_broken": existing_up_broken,
        "classification": classification,
        "level": 0,
    }


def _cluster(
    cluster_id: str,
    *,
    title: str,
    confidence: float,
    candidate_stems: list[str],
    topic_keywords: list[str] | None = None,
    slug: str | None = None,
    location: str = "Atlas/200 Maps/",
    template: str = "t_moc_tomo",
    existing_up: list[dict] | None = None,
) -> dict:
    return {
        "cluster_id": cluster_id,
        "title": title,
        "confidence": confidence,
        "candidate_stems": candidate_stems,
        "topic_keywords": topic_keywords or [],
        "slug": slug or title.lower().replace(" ", "-"),
        "location": location,
        "template": template,
        "existing_up": existing_up or [],
    }


def _empty_report() -> dict:
    return {
        "schema_version": "1",
        "run_id": "test-run-id",
        "mode": "tag",
        "trigger_arg": "topic/applied/test",
        "profile": "miyo",
        "candidates_total": 0,
        "candidates_after_prefilter": 0,
        "candidates_capped": False,
        "candidates": [],
        "topic_clusters": [],
        "parent_options_per_cluster": {},
        "duplicates_skipped": [],
        "squelched": [],
        "abort_reason": None,
        "abort_message": None,
        "extracted_via_llm_count": 0,
        "cache_miss_batches_used": 0,
    }


def _single_cluster_report() -> dict:
    """A minimal single-cluster DiscoveryReport."""
    report = _empty_report()
    report["candidates"] = [_candidate("note-a"), _candidate("note-b")]
    report["topic_clusters"] = [
        _cluster(
            "MOC01",
            title="Shell & Terminal (MOC)",
            confidence=0.78,
            candidate_stems=["note-a", "note-b"],
            slug="shell-terminal-moc",
        )
    ]
    report["parent_options_per_cluster"] = {
        "MOC01": [
            {
                "moc_stem": "2600 - Applied Sciences",
                "confidence": 0.85,
                "label": "Applied Sciences (Dewey 2600)",
            }
        ]
    }
    return report


# ── Tests ────────────────────────────────────────────────────────────────────


def test_dispatch_on_filename_pattern() -> None:
    """filename tomo-moc-proposal-*.md routes to the MOC branch (not S## branch)."""
    report = _single_cluster_report()
    filename, body = render_moc_proposal_doc(report, _Cfg())

    # Verify the filename matches the dispatch pattern
    assert filename.startswith("tomo-moc-proposal-"), f"Unexpected filename: {filename!r}"

    # Parse via the MOC branch using the generated body
    results = parse_moc_proposal_doc(body, filename=filename)

    # Should return a list (ConfirmedMOCProposal[])
    assert isinstance(results, list), f"Expected list, got {type(results)}"


def test_dispatch_on_frontmatter_type() -> None:
    """frontmatter type: tomo-proposal routes to MOC branch independent of filename."""
    report = _single_cluster_report()
    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # The body has `type: tomo-proposal` in frontmatter.
    # Call with a non-matching filename — dispatch must use frontmatter.
    results = parse_moc_proposal_doc(body, filename="some-other-name.md")

    assert isinstance(results, list), f"Expected list from frontmatter dispatch, got {type(results)}"


def test_skip_when_only_some_clusters_accepted() -> None:
    """Multi-cluster doc with 1 of 3 Accept ticked → returns exactly 1 ConfirmedMOCProposal."""
    report = _empty_report()
    report["candidates"] = [_candidate(f"note-{i}") for i in range(5)]
    report["topic_clusters"] = [
        _cluster("MOC01", title="Topic One (MOC)", confidence=0.80,
                 candidate_stems=["note-0", "note-1"], slug="topic-one-moc"),
        _cluster("MOC02", title="Topic Two (MOC)", confidence=0.65,
                 candidate_stems=["note-2", "note-3"], slug="topic-two-moc"),
        _cluster("MOC03", title="Topic Three (MOC)", confidence=0.50,
                 candidate_stems=["note-4"], slug="topic-three-moc"),
    ]
    report["parent_options_per_cluster"] = {}

    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Tick only the first Accept (MOC01 which is highest confidence, rendered first)
    # The rendered body has `- [ ] Accept` lines — tick only the first one
    first_accept_pos = body.index("- [ ] Accept")
    body_one_accepted = (
        body[:first_accept_pos]
        + "- [x] Accept"
        + body[first_accept_pos + len("- [ ] Accept"):]
    )

    results = parse_moc_proposal_doc(body_one_accepted, filename=_filename)

    assert len(results) == 1, (
        f"Expected 1 accepted proposal, got {len(results)}. "
        f"Results: {results}"
    )


def test_no_clusters_accepted_returns_empty() -> None:
    """No Accept ticks → returns [] (eligible for squelch)."""
    report = _single_cluster_report()
    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Do NOT tick any Accept — body has `- [ ] Accept` (unchecked)
    assert "- [ ] Accept" in body, "Fixture must contain unchecked Accept"
    assert "- [x] Accept" not in body, "Fixture must not have Accept ticked by default"

    results = parse_moc_proposal_doc(body, filename=_filename)

    assert results == [], (
        f"Expected empty list when no Accept ticked, got {results}"
    )


def test_parse_children_list_extracts_ticked_only() -> None:
    """Children section: only [x] items extracted, [ ] items ignored."""
    report = _empty_report()
    report["candidates"] = [
        _candidate("note-yes-1"),
        _candidate("note-yes-2"),
        _candidate("note-no-1"),
    ]
    report["topic_clusters"] = [
        _cluster(
            "MOC01",
            title="Children Test (MOC)",
            confidence=0.75,
            candidate_stems=["note-yes-1", "note-yes-2", "note-no-1"],
            slug="children-test-moc",
        )
    ]
    report["parent_options_per_cluster"] = {}

    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Tick Accept for the one cluster
    body_accepted = body.replace("- [ ] Accept", "- [x] Accept", 1)

    # Untick note-no-1 in Children: body has `- [x] \`[[note-no-1]]\``
    body_modified = body_accepted.replace(
        "- [x] `[[note-no-1]]`", "- [ ] `[[note-no-1]]`"
    )

    results = parse_moc_proposal_doc(body_modified, filename=_filename)

    assert len(results) == 1
    children = results[0]["children"]
    assert "note-yes-1" in children, f"note-yes-1 missing from children: {children}"
    assert "note-yes-2" in children, f"note-yes-2 missing from children: {children}"
    assert "note-no-1" not in children, f"note-no-1 should NOT be in children: {children}"


def test_parse_parent_single_select_first_check_wins() -> None:
    """Multiple parent options; only the first checked one is used as parent."""
    report = _empty_report()
    report["candidates"] = [_candidate("note-a")]
    report["topic_clusters"] = [
        _cluster(
            "MOC01",
            title="Parent Test (MOC)",
            confidence=0.80,
            candidate_stems=["note-a"],
            slug="parent-test-moc",
        )
    ]
    # Two parent options — renderer ticks first one [x], second is [ ]
    report["parent_options_per_cluster"] = {
        "MOC01": [
            {"moc_stem": "First Parent", "confidence": 0.90, "label": "First Parent MOC"},
            {"moc_stem": "Second Parent", "confidence": 0.70, "label": "Second Parent MOC"},
        ]
    }

    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Tick Accept
    body_accepted = body.replace("- [ ] Accept", "- [x] Accept", 1)

    results = parse_moc_proposal_doc(body_accepted, filename=_filename)

    assert len(results) == 1
    # First option has [x] in rendered output → wins as parent
    assert results[0]["parent"] == "First Parent", (
        f"Expected 'First Parent' as parent, got {results[0].get('parent')!r}"
    )


def test_parse_override_toggle_extracts_bool() -> None:
    """Ticking 'Bestehende up:: behalten' → override_preserve_existing_up == True."""
    report = _single_cluster_report()
    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Accept the cluster
    body_accepted = body.replace("- [ ] Accept", "- [x] Accept", 1)

    # Tick the override checkbox
    body_override = body_accepted.replace(
        "- [ ] **Bestehende up:: behalten", "- [x] **Bestehende up:: behalten"
    )

    results = parse_moc_proposal_doc(body_override, filename=_filename)

    assert len(results) == 1
    assert results[0].get("override_preserve_existing_up") is True, (
        f"Expected override_preserve_existing_up=True, got "
        f"{results[0].get('override_preserve_existing_up')!r}"
    )


def test_parse_override_toggle_false_by_default() -> None:
    """Unchecked 'Bestehende up:: behalten' → override_preserve_existing_up == False."""
    report = _single_cluster_report()
    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Accept the cluster, do NOT tick the override
    body_accepted = body.replace("- [ ] Accept", "- [x] Accept", 1)

    results = parse_moc_proposal_doc(body_accepted, filename=_filename)

    assert len(results) == 1
    assert results[0].get("override_preserve_existing_up") is False, (
        f"Expected override_preserve_existing_up=False, got "
        f"{results[0].get('override_preserve_existing_up')!r}"
    )


def test_editable_text_fields_extracted() -> None:
    """Title, Location, and Template are extracted from inline **Field:** lines."""
    report = _empty_report()
    report["candidates"] = [_candidate("note-x")]
    report["topic_clusters"] = [
        _cluster(
            "MOC01",
            title="Field Extraction (MOC)",
            confidence=0.85,
            candidate_stems=["note-x"],
            location="Atlas/200 Maps/",
            template="t_moc_tomo",
            slug="field-extraction-moc",
        )
    ]
    report["parent_options_per_cluster"] = {}

    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Accept the cluster
    body_accepted = body.replace("- [ ] Accept", "- [x] Accept", 1)

    results = parse_moc_proposal_doc(body_accepted, filename=_filename)

    assert len(results) == 1
    item = results[0]

    assert item.get("title") == "Field Extraction (MOC)", (
        f"Expected title 'Field Extraction (MOC)', got {item.get('title')!r}"
    )
    assert item.get("location") is not None and "200 Maps" in item["location"], (
        f"Expected location containing '200 Maps', got {item.get('location')!r}"
    )
    assert item.get("template") == "t_moc_tomo", (
        f"Expected template 't_moc_tomo', got {item.get('template')!r}"
    )
