#!/usr/bin/env python3
# version: 0.2.0
"""Round-trip tests for F-41 (XDD 016) T3 — per-atomic-header format.

T2 changed the renderer so every create_atomic_note gets its OWN `### SNN — Title`
header.  Before T2, one `### S01 — Memo split` held N `**Source:**` blocks, and
the parser's `split_section_into_blocks` split them internally.  After T2 the
parser sees N separate sections (one per atomic), each with exactly one Source.

These tests verify the parser still produces N correct confirmed_items with a
shared source_path from the new format.

Scenarios:
  1. Two approved atomics (S01 + S02), same source [[memo]] → 2 confirmed_items
     with identical source_path (C6 delete-gate grouping by source_path relies on
     this).
  2. Single-atomic doc (S01 only) → exactly 1 confirmed_item (regression guard).
  3. Mixed: S01 approved, S02 skipped → only S01 is a confirmed_item; S02 is
     in skipped.
  4. Three approved atomics, two sources (S01+S02 from [[memo]], S03 from
     [[journal]]) → 3 confirmed_items, source_path grouping correct.

Each fixture is generated by calling the REAL renderer (suggestions-render.py
render_suggestions) with reducer-style rendered_md blocks so the round-trip
exercises the exact bytes the pipeline produces.
"""
from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parent.parent
PARSER = REPO_ROOT / "tomo" / "scripts" / "suggestion-parser.py"
SCRIPTS_DIR = REPO_ROOT / "tomo" / "scripts"

sys.path.insert(0, str(SCRIPTS_DIR))


# ──────────────────────────────────────────────────────────────────────
# Renderer loader (mirrors test_suggestions_render_per_atomic_header.py)
# ──────────────────────────────────────────────────────────────────────

def _load_render_mod():
    spec = importlib.util.spec_from_file_location(
        "suggestions_render_t3",
        SCRIPTS_DIR / "suggestions-render.py",
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_RENDER_MOD = _load_render_mod()


# ──────────────────────────────────────────────────────────────────────
# Fixture helpers — mirror reducer's render_create_atomic_note output
# ──────────────────────────────────────────────────────────────────────

_DECISION_BLOCK = (
    "\n"
    "**Decision (atomic note):**\n"
    "- [x] Approve\n"
    "- [ ] Keep origin (skip the implicit delete of the inbox source after move_note)\n"
    "- [ ] Skip (keep in inbox)\n"
    "- [ ] Delete source"
)

_DECISION_BLOCK_SKIP = (
    "\n"
    "**Decision (atomic note):**\n"
    "- [ ] Approve\n"
    "- [ ] Keep origin (skip the implicit delete of the inbox source after move_note)\n"
    "- [x] Skip (keep in inbox)\n"
    "- [ ] Delete source"
)


def _atomic_rendered_md(stem: str, title: str, *, approve: bool = True) -> str:
    """Build a rendered_md string matching reducer's render_create_atomic_note output."""
    decision = _DECISION_BLOCK if approve else _DECISION_BLOCK_SKIP
    return (
        f"**Source:** [[{stem}]]\n"
        f"**Suggested name:** {title}\n"
        "**Template:** [[t_note_tomo]]    ← change if you want a different template\n"
        "**Location:** [[Atlas/202 Notes/]]    ← change if you want a different folder"
        + decision
    )


def _make_action(suggestion_id: str, stem: str, title: str, *, approve: bool = True) -> dict[str, Any]:
    return {
        "kind": "create_atomic_note",
        "suggestion_id": suggestion_id,
        "rendered_md": _atomic_rendered_md(stem, title, approve=approve),
    }


def _make_section(sid: str, stem: str, actions: list[dict[str, Any]]) -> dict[str, Any]:
    return {"id": sid, "stem": stem, "actions": actions}


def _make_doc(sections: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "schema_version": "1",
        "generated": "2026-06-11T10:00:00Z",
        "run_id": "2026-06-11-1000-t3test",
        "profile": "miyo",
        "doc_variant": "primary",
        "source_items": len(sections),
        "sections": sections,
        "daily_notes_updates": [],
        "proposed_mocs": [],
        "needs_attention": [],
    }


def _render_to_markdown(doc: dict[str, Any]) -> str:
    """Run the real renderer and return the Suggestions section as a markdown string."""
    suggestion_lines = _RENDER_MOD.render_suggestions(doc)
    return "\n".join(suggestion_lines)


def _full_doc_markdown(suggestions_md: str, source_items: int) -> str:
    """Wrap suggestions markdown in a minimal valid suggestions doc (frontmatter + header).

    source_items must match the number of sections in the doc (one inbox item
    per section).
    """
    return "\n".join([
        "---",
        "type: tomo-suggestions",
        "generated: 2026-06-11T10:00:00Z",
        'tomo_version: "0.1.0"',
        "profile: miyo",
        f"source_items: {source_items}",
        "run_id: 2026-06-11-1000-t3test",
        "---",
        "",
        "# Inbox Suggestions — 2026-06-11",
        "",
        "- [x] Approved — check this box when you have finished reviewing",
        "",
        "## Summary",
        "",
        f"- Items processed: {source_items}",
        "",
        suggestions_md,
    ])


# ──────────────────────────────────────────────────────────────────────
# Parser runner
# ──────────────────────────────────────────────────────────────────────

def _run_parser(md: str, tmp_path: Path) -> dict:
    p = tmp_path / "suggestions.md"
    p.write_text(md)
    cmd = [sys.executable, str(PARSER), "--file", str(p)]
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    assert result.returncode == 0, (
        f"parser exit {result.returncode}; stderr:\n{result.stderr}"
    )
    return json.loads(result.stdout)


def _stem(src: str | None) -> str:
    if not src:
        return ""
    return src.rsplit("/", 1)[-1].replace(".md", "").strip("[]").lower()


# ──────────────────────────────────────────────────────────────────────
# Tests
# ──────────────────────────────────────────────────────────────────────

class TestPerAtomicHeaderParserRoundTrip:
    """Scenario 1: two approved atomics, same source → two confirmed_items."""

    def test_two_approved_atomics_yield_correct_confirmed_items(self, tmp_path):
        """Two atomics from the same source must each become a confirmed_item
        with the shared source_path and distinct titles (C6 delete-gate groups
        by source_path to offer 'delete [[memo]]?' once, not twice)."""
        doc = _make_doc([
            _make_section("S01", "memo", [
                _make_action("S01", "memo", "First Topic"),
                _make_action("S02", "memo", "Second Topic"),
            ])
        ])
        suggestions_md = _render_to_markdown(doc)
        full_md = _full_doc_markdown(suggestions_md, source_items=1)

        out = _run_parser(full_md, tmp_path)

        memo_items = [
            c for c in out["confirmed_items"]
            if _stem(c.get("source_path")) == "memo"
        ]
        assert len(memo_items) == 2, (
            f"Expected 2 confirmed memo items from new per-atomic-header format, "
            f"got {len(memo_items)}: {memo_items}"
        )
        for item in memo_items:
            assert _stem(item.get("source_path")) == "memo", (
                f"source_path must resolve to 'memo', got: {item.get('source_path')!r}"
            )
        titles = sorted(c["title"] for c in memo_items)
        assert titles == ["First Topic", "Second Topic"], (
            f"Confirmed titles must be distinct, got: {titles}"
        )


class TestSingleAtomicRegressionGuard:
    """Scenario 2: single-atomic doc → exactly 1 confirmed_item."""

    def test_single_atomic_yields_one_item(self, tmp_path):
        doc = _make_doc([
            _make_section("S01", "memo", [
                _make_action("S01", "memo", "Only Topic"),
            ])
        ])
        suggestions_md = _render_to_markdown(doc)
        full_md = _full_doc_markdown(suggestions_md, source_items=1)

        out = _run_parser(full_md, tmp_path)

        memo_items = [
            c for c in out["confirmed_items"]
            if _stem(c.get("source_path")) == "memo"
        ]
        assert len(memo_items) == 1, (
            f"Single-atomic doc must yield exactly 1 confirmed_item, got {memo_items}"
        )
        assert memo_items[0]["title"] == "Only Topic"
        assert memo_items[0]["id"] == "S01"
        assert out.get("total_sections") == 1, (
            f"total_sections must be 1 for single-atomic doc, got {out.get('total_sections')}"
        )


class TestMixedApprovalPerAtomicHeader:
    """Scenario 3: S01 approved, S02 skipped → 1 confirmed_item, 1 skipped."""

    def test_approved_atomic_is_confirmed(self, tmp_path):
        doc = _make_doc([
            _make_section("S01", "memo", [
                _make_action("S01", "memo", "First Topic", approve=True),
                _make_action("S02", "memo", "Second Topic", approve=False),
            ])
        ])
        suggestions_md = _render_to_markdown(doc)
        full_md = _full_doc_markdown(suggestions_md, source_items=1)

        out = _run_parser(full_md, tmp_path)

        memo_confirmed = [
            c for c in out["confirmed_items"]
            if _stem(c.get("source_path")) == "memo"
        ]
        assert len(memo_confirmed) == 1, (
            f"Only the approved atomic must be confirmed, got {memo_confirmed}"
        )
        assert memo_confirmed[0]["title"] == "First Topic", memo_confirmed[0]

    def test_skipped_atomic_lands_in_skipped(self, tmp_path):
        doc = _make_doc([
            _make_section("S01", "memo", [
                _make_action("S01", "memo", "First Topic", approve=True),
                _make_action("S02", "memo", "Second Topic", approve=False),
            ])
        ])
        suggestions_md = _render_to_markdown(doc)
        full_md = _full_doc_markdown(suggestions_md, source_items=1)

        out = _run_parser(full_md, tmp_path)

        memo_skipped = [
            s for s in out["skipped"]
            if _stem(s.get("source_path")) == "memo"
        ]
        assert len(memo_skipped) == 1, (
            f"The unapproved atomic must appear in skipped, got {memo_skipped}"
        )
        assert memo_skipped[0]["id"] == "S02", (
            f"The skipped item must be S02 (Second Topic), got id={memo_skipped[0].get('id')!r}"
        )


class TestMultiSourceGrouping:
    """Scenario 4: three atomics from two sources, grouping correct."""

    def test_three_atomics_two_sources_correct_grouping(self, tmp_path):
        """S01+S02 from [[memo]], S03 from [[journal]] → 3 confirmed_items,
        source_path grouping intact for C6 delete-gate."""
        doc = _make_doc([
            _make_section("S01", "memo", [
                _make_action("S01", "memo", "Memo Alpha"),
                _make_action("S02", "memo", "Memo Beta"),
            ]),
            _make_section("S03", "journal", [
                _make_action("S03", "journal", "Journal Gamma"),
            ]),
        ])
        suggestions_md = _render_to_markdown(doc)
        full_md = _full_doc_markdown(suggestions_md, source_items=2)

        out = _run_parser(full_md, tmp_path)

        confirmed = out["confirmed_items"]
        assert len(confirmed) == 3, (
            f"Expected 3 confirmed_items for 3 approved atomics, got {len(confirmed)}: {confirmed}"
        )

        memo_items = [c for c in confirmed if _stem(c.get("source_path")) == "memo"]
        journal_items = [c for c in confirmed if _stem(c.get("source_path")) == "journal"]

        assert len(memo_items) == 2, (
            f"2 memo atomics expected, got {len(memo_items)}: {memo_items}"
        )
        assert len(journal_items) == 1, (
            f"1 journal atomic expected, got {len(journal_items)}: {journal_items}"
        )

        memo_titles = sorted(c["title"] for c in memo_items)
        assert memo_titles == ["Memo Alpha", "Memo Beta"], memo_titles
        assert journal_items[0]["title"] == "Journal Gamma"
