#!/usr/bin/env python3
# version: 0.2.0
"""test_vault_explorer_step9_scanner.py — Contract test for vault-explorer.md Step 9
orchestration (spec 021, T3.3 / F-34 Condition B retirement).

vault-explorer.md is an LLM-loaded runtime agent spec (not a Python module).
Accumulation (Condition B) was retired per spec 021 ADR-10. These tests assert the
Step 9 region NO LONGER contains the accumulation scaffolding, while the surviving
cache-generation invariants remain intact:

  (a) atomic-note-indexer.py is NOT invoked in Step 9 (producer retired).
  (b) cache-builder.py is NOT passed --accumulation (flag retired).
  (c) No "accumulation" prose remains in the Step 9 region.
  (d) moc-tree-builder.py still runs in Step 9 (force-rebuilds the MOC-structure cache
      as a side effect — ADR-3).
  (e) The existing STRICT cache rule ("cache MUST be generated by cache-builder.py")
      is still present.
  (f) No 2>&1 redirect into a JSON-captured file (memory: feedback_never_redirect_stderr_into_json).
  (g) # version: is number-only and present.

Assertions use substring/offset checks against an isolated Step 9 region.
"""
from __future__ import annotations

import re
from pathlib import Path

TESTS_DIR = Path(__file__).resolve().parent
REPO_ROOT = TESTS_DIR.parent
AGENT_PATH = REPO_ROOT / "tomo" / "dot_claude" / "agents" / "vault-explorer.md"

# Step 9 heading and the heading that follows it (Step 10) to bound the region.
STEP9_HEADING = "### Step 9"
STEP10_HEADING = "### Step 10"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _agent_text() -> str:
    assert AGENT_PATH.exists(), f"Agent file not found: {AGENT_PATH}"
    return AGENT_PATH.read_text()


def _step9_region(text: str) -> str:
    """Return only the text between '### Step 9' and '### Step 10' headings."""
    start = text.find(STEP9_HEADING)
    assert start != -1, f"{STEP9_HEADING!r} not found in vault-explorer.md"
    end = text.find(STEP10_HEADING, start)
    assert end != -1, f"{STEP10_HEADING!r} not found after Step 9 start"
    region = text[start:end]
    assert len(region) > 100, (
        f"Step 9 region is suspiciously short ({len(region)} chars) — "
        "check STEP9_HEADING / STEP10_HEADING markers"
    )
    return region


# ---------------------------------------------------------------------------
# (a) atomic-note-indexer.py is NOT invoked in Step 9 (accumulation retired)
# ---------------------------------------------------------------------------

def test_step9_does_not_invoke_atomic_note_indexer():
    """Step 9 must NOT call atomic-note-indexer.py — accumulation producer retired (021 ADR-10)."""
    text = _agent_text()
    region = _step9_region(text)
    assert "atomic-note-indexer.py" not in region, (
        "Step 9 region still invokes atomic-note-indexer.py — accumulation producer "
        "must be removed (T3.3)"
    )


# ---------------------------------------------------------------------------
# (b) cache-builder.py is NOT passed --accumulation in Step 9
# ---------------------------------------------------------------------------

def test_step9_cache_builder_has_no_accumulation_flag():
    """cache-builder.py in Step 9 must NOT be invoked with --accumulation (flag retired)."""
    text = _agent_text()
    region = _step9_region(text)
    assert "--accumulation" not in region, (
        "Step 9 region still passes --accumulation to cache-builder.py — must be removed (T3.3)"
    )


# ---------------------------------------------------------------------------
# (c) No accumulation prose remains in Step 9
# ---------------------------------------------------------------------------

def test_step9_no_accumulation_prose():
    """No 'accumulation' reference may remain in the Step 9 region."""
    text = _agent_text()
    region = _step9_region(text)
    assert "accumulation" not in region.lower(), (
        "Step 9 region still references 'accumulation' — all Condition B text must be removed (T3.3)"
    )


# ---------------------------------------------------------------------------
# (d) moc-tree-builder.py still runs in Step 9 (force-rebuilds MOC-structure cache)
# ---------------------------------------------------------------------------

def test_step9_runs_moc_tree_builder():
    """Step 9 must still run moc-tree-builder.py — it force-rebuilds the MOC-structure
    cache as a side effect (ADR-3)."""
    text = _agent_text()
    region = _step9_region(text)
    assert "moc-tree-builder.py" in region, (
        "Step 9 region must still invoke moc-tree-builder.py (force-rebuilds MOC-structure cache)"
    )


# ---------------------------------------------------------------------------
# (e) STRICT cache rule is preserved
# ---------------------------------------------------------------------------

def test_step9_strict_cache_rule_preserved():
    """The existing STRICT rule that cache MUST be generated by cache-builder.py must survive."""
    text = _agent_text()
    region = _step9_region(text)

    has_strict = "STRICT" in region
    has_cache_builder_ref = "cache-builder.py" in region

    assert has_strict, (
        "Step 9 STRICT block must be preserved — "
        "cache MUST be generated by cache-builder.py, not written by hand"
    )
    assert has_cache_builder_ref, (
        "Step 9 region must still reference cache-builder.py in the STRICT rule"
    )

    strict_pos = region.find("STRICT")
    builder_in_strict_window = "cache-builder.py" in region[strict_pos: strict_pos + 300]
    assert builder_in_strict_window, (
        "The STRICT block must reference cache-builder.py within its text (within 300 chars)"
    )


# ---------------------------------------------------------------------------
# (f) No 2>&1 redirect into a JSON-captured file
# ---------------------------------------------------------------------------

def test_step9_no_stderr_redirect_into_json_capture():
    """Step 9 must NOT merge stderr into the stdout-captured JSON file (2>&1 on scanner line)."""
    text = _agent_text()
    region = _step9_region(text)

    json_redirect_lines = [
        line for line in region.splitlines()
        if re.search(r'>\s*["\']?[^"\']*\.json["\']?', line)
    ]

    for line in json_redirect_lines:
        assert "2>&1" not in line, (
            f"Step 9 must not redirect stderr into a JSON-captured file. "
            f"Found: {line!r}"
        )


# ---------------------------------------------------------------------------
# (g) # version: present and number-only
# ---------------------------------------------------------------------------

def test_vault_explorer_version_present():
    """vault-explorer.md must have a '# version: X.Y.Z' comment."""
    text = _agent_text()
    match = re.search(r"#\s*version:\s*(\d+)\.(\d+)\.(\d+)", text)
    assert match, "vault-explorer.md must have a '# version: X.Y.Z' comment"


def test_vault_explorer_version_no_parenthetical():
    """Version comment must be number-only — no parenthetical after the version number."""
    text = _agent_text()
    for line in text.splitlines():
        if "version:" in line and re.search(r"#\s*version:", line):
            assert "(" not in line, (
                f"Version comment must be number-only, no parenthetical. Found: {line!r}"
            )
