#!/usr/bin/env python3
# version: 0.2.0
"""test-vault-config-writer.py — Unit tests for vault-config-writer.py.

Covers:
  - JSON input validation (accept/reject the right shapes)
  - Rendering contract (output matches vault-example.yaml-style formatting)
  - Section replacement (only the `tags:` block changes; everything else stays
    byte-for-byte)
  - End-to-end: replacement → yaml.safe_load → matches the input dict
  - First-write path (no existing `tags:` section → append)
"""
from __future__ import annotations

import importlib.util
import json
import sys
import tempfile
from pathlib import Path

import yaml

TESTS_DIR = Path(__file__).resolve().parent
REPO_ROOT = TESTS_DIR.parent
SCRIPTS_DIR = REPO_ROOT / "tomo" / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))

_spec = importlib.util.spec_from_file_location(
    "vault_config_writer", SCRIPTS_DIR / "vault-config-writer.py"
)
vcw = importlib.util.module_from_spec(_spec)
assert _spec.loader is not None
_spec.loader.exec_module(vcw)


# ──────────────────────────────────────────────────────────────────────────────
# Fixtures
# ──────────────────────────────────────────────────────────────────────────────

VALID_INPUT = {
    "prefixes": {
        "type": {
            "description": "Note type (structural)",
            "known_values": ["note/normal", "others/moc"],
            "wildcard": False,
            "proposable": True,
            "required_for": ["atomic_note", "map_note"],
        },
        "topic": {
            "description": "Topic area (free-form, hierarchical)",
            "known_values": ["knowledge/lyt", "applied/ai"],
            "wildcard": True,
            "proposable": True,
            "required_for": [],
        },
        "Raindrop": {
            "description": "Raindrop.io import — external taxonomy; Tomo does not manage.",
            "known_values": ["Obsidian", "japan"],
            "wildcard": False,
            "proposable": False,
            "required_for": [],
        },
        "status": {
            "description": "Note status (covers empty-known_values path)",
            "known_values": [],
            "wildcard": True,
            "proposable": True,
            "required_for": [],
        },
    }
}

SAMPLE_CONFIG_WITH_TAGS = """\
# Generated by install-tomo.sh
schema_version: 1

profile: "miyo"

concepts:
  inbox: "100 Inbox/"

tags:
  prefixes:
    - type
    - status
    - topic
  total_unique: 287

lifecycle:
  tag_prefix: "MiYo-Tomo"
"""

SAMPLE_CONFIG_WITHOUT_TAGS = """\
schema_version: 1
profile: "miyo"
concepts:
  inbox: "100 Inbox/"
lifecycle:
  tag_prefix: "MiYo-Tomo"
"""


def _must(cond: bool, msg: str) -> None:
    if not cond:
        print(f"FAIL: {msg}", file=sys.stderr)
        sys.exit(1)


def _expect_fail(fn, *args, label: str = "") -> None:
    """Call fn(*args) and assert it calls sys.exit(1) (validation failure)."""
    try:
        fn(*args)
    except SystemExit as e:
        _must(e.code == 1, f"{label}: expected exit 1, got {e.code}")
        return
    _must(False, f"{label}: expected validation failure, got success")


# ──────────────────────────────────────────────────────────────────────────────
# Validation tests
# ──────────────────────────────────────────────────────────────────────────────

def test_validation_accepts_valid():
    # Should not raise
    vcw.validate_tags_input(VALID_INPUT)
    print("[PASS] validation accepts the canonical shape")


def test_validation_rejects_list_shape():
    """The exact bug that blocked Pass 1."""
    _expect_fail(
        vcw.validate_tags_input,
        {"prefixes": ["type", "status", "topic"]},
        label="list-shape prefixes",
    )
    print("[PASS] validation rejects list-of-strings (regression guard)")


def test_validation_rejects_missing_fields():
    bad = {
        "prefixes": {
            "type": {
                "description": "x",
                "known_values": [],
                "wildcard": True,
                "proposable": True,
                # missing required_for
            }
        }
    }
    _expect_fail(vcw.validate_tags_input, bad, label="missing required_for")
    print("[PASS] validation rejects entries missing required fields")


def test_validation_rejects_missing_proposable():
    """Regression guard for the 2-axis → 3-axis migration."""
    bad = {
        "prefixes": {
            "type": {
                "description": "x",
                "known_values": [],
                "wildcard": True,
                "required_for": [],
                # missing proposable
            }
        }
    }
    _expect_fail(vcw.validate_tags_input, bad, label="missing proposable")
    print("[PASS] validation rejects entries missing proposable (migration guard)")


def test_validation_rejects_extra_fields():
    bad = {
        "prefixes": {
            "type": {
                "description": "x", "known_values": [], "wildcard": True,
                "proposable": True, "required_for": [], "bogus": 1,
            }
        }
    }
    _expect_fail(vcw.validate_tags_input, bad, label="extra fields")
    print("[PASS] validation rejects unknown per-prefix fields")


def test_validation_rejects_bad_required_for():
    bad = {
        "prefixes": {
            "type": {
                "description": "x", "known_values": [], "wildcard": True,
                "proposable": True, "required_for": ["notathing"],
            }
        }
    }
    _expect_fail(vcw.validate_tags_input, bad, label="bad concept in required_for")
    print("[PASS] validation rejects unknown concepts in required_for")


def test_validation_rejects_non_bool_wildcard():
    bad = {
        "prefixes": {
            "type": {
                "description": "x", "known_values": [], "wildcard": "true",
                "proposable": True, "required_for": [],
            }
        }
    }
    _expect_fail(vcw.validate_tags_input, bad, label="string wildcard")
    print("[PASS] validation rejects non-bool wildcard (string 'true')")


def test_validation_rejects_non_bool_proposable():
    bad = {
        "prefixes": {
            "type": {
                "description": "x", "known_values": [], "wildcard": True,
                "proposable": "yes", "required_for": [],
            }
        }
    }
    _expect_fail(vcw.validate_tags_input, bad, label="string proposable")
    print("[PASS] validation rejects non-bool proposable")


# ──────────────────────────────────────────────────────────────────────────────
# Rendering tests
# ──────────────────────────────────────────────────────────────────────────────

def test_render_format_contract():
    out = vcw.render_tags_section(VALID_INPUT)
    # Top structure
    _must(out.startswith("tags:\n  prefixes:\n"), "render must start with tags: / prefixes:")
    _must(out.endswith("\n"), "render must end with a newline")
    # Per-entry fields
    for name in VALID_INPUT["prefixes"]:
        _must(f"    {name}:" in out, f"missing prefix key line for {name}")
    # Double-quoted strings
    _must('"Note type (structural)"' in out, "description must be double-quoted")
    _must('"note/normal"' in out, "known_values must be double-quoted")
    # Empty lists inline
    _must("known_values: []" in out, "empty known_values should be inline []")
    _must("required_for: []" in out, "empty required_for should be inline []")
    # Booleans lowercase
    _must("wildcard: false" in out, "wildcard false should be lowercase")
    _must("wildcard: true" in out, "wildcard true should be lowercase")
    _must("proposable: false" in out, "proposable false should be lowercase")
    _must("proposable: true" in out, "proposable true should be lowercase")
    # required_for entries as bare tokens (no quotes)
    _must("        - atomic_note" in out, "required_for items should be bare tokens")
    print("[PASS] render format matches vault-example.yaml conventions")


def test_render_is_valid_yaml():
    out = vcw.render_tags_section(VALID_INPUT)
    parsed = yaml.safe_load(out)
    _must("tags" in parsed and "prefixes" in parsed["tags"],
          "rendered YAML must parse with tags.prefixes")
    prefixes = parsed["tags"]["prefixes"]
    _must(isinstance(prefixes, dict), "parsed prefixes must be dict")
    _must(set(prefixes) == set(VALID_INPUT["prefixes"]),
          f"prefix keys mismatch: {set(prefixes)} vs {set(VALID_INPUT['prefixes'])}")
    for name, entry in VALID_INPUT["prefixes"].items():
        got = prefixes[name]
        _must(got["wildcard"] == entry["wildcard"], f"{name}: wildcard mismatch")
        _must(got["proposable"] == entry["proposable"], f"{name}: proposable mismatch")
        _must(got["known_values"] == entry["known_values"], f"{name}: known_values mismatch")
        _must(got["required_for"] == entry["required_for"], f"{name}: required_for mismatch")
        _must(got["description"] == entry["description"], f"{name}: description mismatch")
    print("[PASS] rendered YAML parses back to the input dict")


# ──────────────────────────────────────────────────────────────────────────────
# Section replacement tests
# ──────────────────────────────────────────────────────────────────────────────

def test_replace_existing_section():
    new_block = vcw.render_tags_section(VALID_INPUT)
    updated = vcw.replace_top_level_section(SAMPLE_CONFIG_WITH_TAGS, "tags", new_block)
    # Surrounding content preserved exactly
    _must("# Generated by install-tomo.sh" in updated, "comment above preserved")
    _must('profile: "miyo"' in updated, "profile line preserved")
    _must('tag_prefix: "MiYo-Tomo"' in updated, "lifecycle section preserved")
    # Old list-shape must be gone
    _must("- type\n" not in updated, "old flat-list entry `- type` should be replaced")
    _must("total_unique: 287" not in updated, "stale total_unique must not leak through")
    # New dict-shape present
    _must("wildcard: false" in updated, "new content present")
    # Result parses and has the new shape
    parsed = yaml.safe_load(updated)
    _must(isinstance(parsed["tags"]["prefixes"], dict), "tags.prefixes must now be dict")
    print("[PASS] replace: old list-shape removed, dict-shape written, neighbours intact")


def test_append_when_missing():
    new_block = vcw.render_tags_section(VALID_INPUT)
    updated = vcw.replace_top_level_section(SAMPLE_CONFIG_WITHOUT_TAGS, "tags", new_block)
    # Original content preserved
    _must("schema_version: 1" in updated, "original content preserved")
    _must('tag_prefix: "MiYo-Tomo"' in updated, "lifecycle preserved")
    # New tags block present at end (or at least present)
    _must("tags:" in updated, "tags block appended")
    parsed = yaml.safe_load(updated)
    _must(isinstance(parsed["tags"]["prefixes"], dict), "appended tags.prefixes must be dict")
    print("[PASS] append: new tags section added when none existed")


def test_replace_preserves_neighbours_bytewise():
    """Byte-level check: lines OUTSIDE tags: must be identical."""
    before = SAMPLE_CONFIG_WITH_TAGS.splitlines()
    new_block = vcw.render_tags_section(VALID_INPUT)
    updated = vcw.replace_top_level_section(SAMPLE_CONFIG_WITH_TAGS, "tags", new_block)
    after = updated.splitlines()

    # Everything before `tags:` (in original) must appear verbatim at the same
    # relative position in the output.
    def until_tags(lines):
        head = []
        for ln in lines:
            if ln.rstrip() == "tags:":
                break
            head.append(ln)
        return head

    def after_tags(lines):
        """Lines after the tags block — i.e., next top-level key onward."""
        out = []
        in_tags = False
        past_tags = False
        for ln in lines:
            if not in_tags and ln.rstrip() == "tags:":
                in_tags = True
                continue
            if in_tags and not past_tags:
                if ln == "" or ln.startswith((" ", "\t")):
                    continue
                past_tags = True
            if past_tags:
                out.append(ln)
        return out

    _must(until_tags(before) == until_tags(after),
          "head (before tags:) must match byte-for-byte")
    _must(after_tags(before) == after_tags(after),
          "tail (after tags:) must match byte-for-byte")
    print("[PASS] replace: content outside tags: is byte-identical")


# ──────────────────────────────────────────────────────────────────────────────
# End-to-end (subprocess via cmd_tags)
# ──────────────────────────────────────────────────────────────────────────────

def test_end_to_end_file_roundtrip():
    """Run cmd_tags against a real file → reparse → match input."""
    with tempfile.TemporaryDirectory() as td:
        td_path = Path(td)
        cfg_path = td_path / "vault-config.yaml"
        cfg_path.write_text(SAMPLE_CONFIG_WITH_TAGS, encoding="utf-8")
        input_path = td_path / "tags.json"
        input_path.write_text(json.dumps(VALID_INPUT), encoding="utf-8")

        class Args:
            input = str(input_path)
            config = str(cfg_path)
            stdout = False

        rc = vcw.cmd_tags(Args())
        _must(rc == 0, f"cmd_tags returned non-zero: {rc}")

        reparsed = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
        _must(isinstance(reparsed["tags"]["prefixes"], dict),
              "post-write YAML must have tags.prefixes as dict")
        _must(set(reparsed["tags"]["prefixes"]) == set(VALID_INPUT["prefixes"]),
              "post-write prefix set must match input")
        # Also confirm unrelated sections survived
        _must(reparsed["profile"] == "miyo", "profile preserved")
        _must(reparsed["lifecycle"]["tag_prefix"] == "MiYo-Tomo", "lifecycle preserved")
    print("[PASS] end-to-end: file written, reparsed, unrelated sections preserved")


# ──────────────────────────────────────────────────────────────────────────────
# relationships subcommand
# ──────────────────────────────────────────────────────────────────────────────

VALID_RELATIONSHIPS = {
    "parent": {
        "marker": "up::", "format": "up:: {{link}}",
        "position": "connect_callout", "location_type": "inline",
        "multi": True, "separator": ", ",
    },
    "peer": {
        "marker": "related::", "format": "related:: {{link}}",
        "position": "connect_callout", "location_type": "inline",
        "multi": True, "separator": ", ",
    },
}


def test_relationships_render_and_roundtrip():
    vcw.validate_relationships_input(VALID_RELATIONSHIPS)
    out = vcw.render_relationships_section(VALID_RELATIONSHIPS)
    _must(out.startswith("relationships:\n"), "must start with relationships:")
    parsed = yaml.safe_load(out)
    _must(set(parsed["relationships"]) == {"parent", "peer"}, "roundtrip keys")
    _must(parsed["relationships"]["parent"]["multi"] is True, "parent.multi bool")
    _must(parsed["relationships"]["parent"]["format"] == "up:: {{link}}", "format preserved")
    print("[PASS] relationships — valid input renders + roundtrips")


def test_relationships_rejects_missing_link_token():
    bad = {"parent": {**VALID_RELATIONSHIPS["parent"], "format": "up:: LINK"}}
    _expect_fail(vcw.validate_relationships_input, bad,
                 label="format without {{link}} token")
    print("[PASS] relationships — format must contain {{link}}")


def test_relationships_rejects_bad_position():
    bad = {"parent": {**VALID_RELATIONSHIPS["parent"], "position": "anywhere"}}
    _expect_fail(vcw.validate_relationships_input, bad, label="bad position enum")
    print("[PASS] relationships — position enum enforced")


# ──────────────────────────────────────────────────────────────────────────────
# callouts subcommand
# ──────────────────────────────────────────────────────────────────────────────

VALID_CALLOUTS = {
    "enabled": True,
    "editable": {
        "connect": "Navigation breadcrumbs",
        "blocks": "Key Concepts section",
    },
    "protected": {
        "shell": "DataviewJS output — do not touch",
    },
    "ignore": {
        "weather": "Decorative widget",
    },
}


def test_callouts_render_and_roundtrip():
    vcw.validate_callouts_input(VALID_CALLOUTS)
    out = vcw.render_callouts_section(VALID_CALLOUTS)
    _must(out.startswith("callouts:\n"), "must start with callouts:")
    _must("enabled: true" in out, "enabled rendered as true")
    parsed = yaml.safe_load(out)
    _must(parsed["callouts"]["enabled"] is True, "enabled bool preserved")
    _must(parsed["callouts"]["editable"]["connect"] == "Navigation breadcrumbs",
          "editable description preserved")
    _must(parsed["callouts"]["protected"]["shell"].startswith("DataviewJS"),
          "protected description preserved")
    print("[PASS] callouts — valid input renders + roundtrips")


def test_callouts_rejects_missing_enabled():
    bad = {"editable": {"connect": "x"}}
    _expect_fail(vcw.validate_callouts_input, bad, label="missing enabled")
    print("[PASS] callouts — enabled required")


def test_callouts_rejects_non_bool_enabled():
    bad = {"enabled": "yes"}
    _expect_fail(vcw.validate_callouts_input, bad, label="enabled must be bool")
    print("[PASS] callouts — enabled must be bool")


def test_callouts_omits_empty_buckets():
    out = vcw.render_callouts_section({"enabled": True, "editable": {"connect": "x"}})
    _must("editable:" in out, "editable rendered")
    _must("protected:" not in out, "empty protected bucket omitted")
    _must("ignore:" not in out, "empty ignore bucket omitted")
    print("[PASS] callouts — empty buckets omitted from output")


# ──────────────────────────────────────────────────────────────────────────────
# trackers subcommand
# ──────────────────────────────────────────────────────────────────────────────

VALID_TRACKERS = {
    "daily_note_trackers": {
        "section": "Habit",
        "today_fields": [
            {
                "name": "Sport", "type": "boolean", "syntax": "task_checkbox",
                "description": "Physical exercise the user actually did today.",
                "positive_keywords": ["ran", "gym"],
                "negative_keywords": ["watched video about"],
            },
            {
                "name": "WakeUpEnergy", "type": "integer", "syntax": "inline_field",
                "scale": "1-5",
                "description": "How rested the user felt on waking.",
            },
        ],
    },
    "end_of_day_fields": {
        "section": "End of the Day",
        "fields": [
            {
                "name": "Sleep", "type": "integer", "syntax": "inline_field",
                "scale": "hours",
                "description": "Hours of sleep the night before.",
            },
        ],
    },
}


def test_trackers_render_and_roundtrip():
    vcw.validate_trackers_input(VALID_TRACKERS)
    out = vcw.render_trackers_section(VALID_TRACKERS)
    _must(out.startswith("trackers:\n"), "must start with trackers:")
    parsed = yaml.safe_load(out)
    today = parsed["trackers"]["daily_note_trackers"]["today_fields"]
    _must(len(today) == 2, f"expected 2 today_fields, got {len(today)}")
    _must(today[0]["name"] == "Sport", "first field name preserved")
    _must(today[0]["syntax"] == "task_checkbox", "syntax preserved")
    _must(today[1]["scale"] == "1-5", "scale preserved")
    # positive_keywords roundtrip
    _must(today[0]["positive_keywords"] == ["ran", "gym"], "keywords list preserved")
    eod = parsed["trackers"]["end_of_day_fields"]["fields"]
    _must(eod[0]["name"] == "Sleep", "end-of-day field preserved")
    print("[PASS] trackers — valid input renders + roundtrips")


def test_trackers_rejects_missing_description():
    bad = {
        "daily_note_trackers": {
            "today_fields": [{"name": "X", "type": "boolean", "syntax": "inline_field"}]
        }
    }
    _expect_fail(vcw.validate_trackers_input, bad, label="field without description")
    print("[PASS] trackers — description required per field")


def test_trackers_rejects_bad_syntax():
    bad = {
        "daily_note_trackers": {
            "today_fields": [{
                "name": "X", "type": "boolean", "syntax": "unknown",
                "description": "x",
            }]
        }
    }
    _expect_fail(vcw.validate_trackers_input, bad, label="syntax enum violation")
    print("[PASS] trackers — syntax enum enforced")


def test_trackers_optional_end_of_day_fields():
    minimal = {
        "daily_note_trackers": {
            "today_fields": [
                {"name": "X", "type": "boolean", "syntax": "inline_field",
                 "description": "x"}
            ]
        }
    }
    vcw.validate_trackers_input(minimal)
    out = vcw.render_trackers_section(minimal)
    _must("end_of_day_fields" not in out, "end_of_day_fields must be omitted when absent")
    print("[PASS] trackers — end_of_day_fields optional")


# ──────────────────────────────────────────────────────────────────────────────
# Integration — all 3 new sections survive in one vault-config round-trip
# ──────────────────────────────────────────────────────────────────────────────

def test_all_sections_stack_in_one_config():
    """Apply tags + relationships + callouts + trackers in sequence and verify
    each section lands without clobbering the others."""
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        td_path = Path(td)
        cfg_path = td_path / "vault-config.yaml"
        cfg_path.write_text("schema_version: 1\nprofile: miyo\n", encoding="utf-8")

        # Apply each section
        for section, input_data, validator, renderer in [
            ("tags", VALID_INPUT, vcw.validate_tags_input, vcw.render_tags_section),
            ("relationships", VALID_RELATIONSHIPS, vcw.validate_relationships_input, vcw.render_relationships_section),
            ("callouts", VALID_CALLOUTS, vcw.validate_callouts_input, vcw.render_callouts_section),
            ("trackers", VALID_TRACKERS, vcw.validate_trackers_input, vcw.render_trackers_section),
        ]:
            validator(input_data)
            block = renderer(input_data)
            current = cfg_path.read_text(encoding="utf-8")
            updated = vcw.replace_top_level_section(current, section, block)
            cfg_path.write_text(updated, encoding="utf-8")

        final = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
        for section in ("tags", "relationships", "callouts", "trackers"):
            _must(section in final, f"{section} missing from final config")
        _must(final["profile"] == "miyo", "profile preserved")
        _must(final["schema_version"] == 1, "schema_version preserved")
    print("[PASS] all 4 sections coexist in a single vault-config.yaml")


def main() -> int:
    # tags
    test_validation_accepts_valid()
    test_validation_rejects_list_shape()
    test_validation_rejects_missing_fields()
    test_validation_rejects_missing_proposable()
    test_validation_rejects_extra_fields()
    test_validation_rejects_bad_required_for()
    test_validation_rejects_non_bool_wildcard()
    test_validation_rejects_non_bool_proposable()
    test_render_format_contract()
    test_render_is_valid_yaml()
    test_replace_existing_section()
    test_append_when_missing()
    test_replace_preserves_neighbours_bytewise()
    test_end_to_end_file_roundtrip()
    # relationships
    test_relationships_render_and_roundtrip()
    test_relationships_rejects_missing_link_token()
    test_relationships_rejects_bad_position()
    # callouts
    test_callouts_render_and_roundtrip()
    test_callouts_rejects_missing_enabled()
    test_callouts_rejects_non_bool_enabled()
    test_callouts_omits_empty_buckets()
    # trackers
    test_trackers_render_and_roundtrip()
    test_trackers_rejects_missing_description()
    test_trackers_rejects_bad_syntax()
    test_trackers_optional_end_of_day_fields()
    # integration
    test_all_sections_stack_in_one_config()
    print("\n\u2713 All vault-config-writer tests passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
