#!/usr/bin/env python3
# version: 0.2.0
"""test_suggestion_parser_moc_branch.py — T4.1 + T5.1: MOC proposal-doc pre-parse dispatch.

T4.1 tests (8) cover the original `parse_moc_proposal_doc` branch.
T5.1 tests (5) cover the new tomo.doc_type-based dispatch and ticked/unticked split:

  T4.1:
  test_dispatch_on_filename_pattern        — filename tomo-moc-proposal-*.md routes to MOC branch
  test_dispatch_on_frontmatter_type        — frontmatter type: tomo-proposal routes to MOC branch
  test_skip_when_only_some_clusters_accepted — multi-cluster doc, 1 of 3 accepted → len == 1
  test_no_clusters_accepted_returns_empty  — no Accept ticks → returns []
  test_parse_children_list_extracts_ticked_only — only [x] children extracted
  test_parse_parent_single_select_first_check_wins — multiple parent ticks, first wins
  test_parse_override_toggle_extracts_bool — override ticked → override_preserve_existing_up True
  test_editable_text_fields_extracted      — Title/Location/Template extracted

  T5.1:
  test_dispatch_classified_as_moc_proposal_via_tomo_doc_type — tomo.doc_type=moc-proposal (no matching filename) → MOC branch (returns clusters tuple)
  test_enumerate_returns_only_ticked_clusters — 3 MOC blocks, 2 ticked, 1 not → split correctly
  test_child_wikilinks_extracted_per_cluster — cluster dict has children: [...] with wikilinks
  test_unticked_clusters_returned_separately_for_squelch — unticked clusters carry topic_signature key
  test_filename_heuristic_fallback_still_works — no tomo: block + old filename → still MOC branch

Fixtures are generated by importing `render_moc_proposal_doc` from
`suggestions-reducer.py` with a DiscoveryReport skeleton, following the
pattern in `tests/test_reducer_moc_proposal_mode.py` (per
feedback_fixture_from_live_render.md).
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

TESTS_DIR = Path(__file__).resolve().parent
REPO_ROOT = TESTS_DIR.parent
SCRIPTS_DIR = REPO_ROOT / "tomo" / "scripts"

sys.path.insert(0, str(SCRIPTS_DIR))

# ── Load suggestion-parser.py as a module (hyphen → importlib) ─────────────

_PARSER_PATH = SCRIPTS_DIR / "suggestion-parser.py"
_parser_spec = importlib.util.spec_from_file_location("suggestion_parser", _PARSER_PATH)
_parser_mod = importlib.util.module_from_spec(_parser_spec)
assert _parser_spec.loader is not None
sys.modules["suggestion_parser"] = _parser_mod
_parser_spec.loader.exec_module(_parser_mod)

parse_moc_proposal_doc = _parser_mod.parse_moc_proposal_doc  # type: ignore[attr-defined]
enumerate_moc_sections_split = _parser_mod.enumerate_moc_sections_split  # type: ignore[attr-defined]
_is_moc_proposal_doc = _parser_mod._is_moc_proposal_doc  # type: ignore[attr-defined]

# ── Load suggestions-reducer.py for live fixture generation ─────────────────

_REDUCER_PATH = SCRIPTS_DIR / "suggestions-reducer.py"
_reducer_spec = importlib.util.spec_from_file_location("suggestions_reducer", _REDUCER_PATH)
_reducer_mod = importlib.util.module_from_spec(_reducer_spec)
assert _reducer_spec.loader is not None
sys.modules["suggestions_reducer"] = _reducer_mod
_reducer_spec.loader.exec_module(_reducer_mod)

render_moc_proposal_doc = _reducer_mod.render_moc_proposal_doc  # type: ignore[attr-defined]


# ── Stub config ──────────────────────────────────────────────────────────────

class _Cfg:
    def __init__(self, max_results: int = 5):
        self.max_results = max_results


# ── Report builder helpers (mirrored from test_reducer_moc_proposal_mode.py) ─


def _candidate(
    stem: str,
    *,
    existing_up: str | None = None,
    existing_up_broken: bool = False,
    topics: list[str] | None = None,
    classification: str | None = None,
) -> dict:
    return {
        "stem": stem,
        "path": f"Atlas/202 Notes/{stem}.md",
        "topics": topics or [],
        "existing_up": existing_up,
        "existing_up_broken": existing_up_broken,
        "classification": classification,
        "level": 0,
    }


def _cluster(
    cluster_id: str,
    *,
    title: str,
    confidence: float,
    candidate_stems: list[str],
    topic_keywords: list[str] | None = None,
    slug: str | None = None,
    location: str = "Atlas/200 Maps/",
    template: str = "t_moc_tomo",
    existing_up: list[dict] | None = None,
) -> dict:
    return {
        "cluster_id": cluster_id,
        "title": title,
        "confidence": confidence,
        "candidate_stems": candidate_stems,
        "topic_keywords": topic_keywords or [],
        "slug": slug or title.lower().replace(" ", "-"),
        "location": location,
        "template": template,
        "existing_up": existing_up or [],
    }


def _empty_report() -> dict:
    return {
        "schema_version": "1",
        "run_id": "test-run-id",
        "mode": "tag",
        "trigger_arg": "topic/applied/test",
        "profile": "miyo",
        "candidates_total": 0,
        "candidates_after_prefilter": 0,
        "candidates_capped": False,
        "candidates": [],
        "topic_clusters": [],
        "parent_options_per_cluster": {},
        "duplicates_skipped": [],
        "squelched": [],
        "abort_reason": None,
        "abort_message": None,
        "extracted_via_llm_count": 0,
        "cache_miss_batches_used": 0,
    }


def _single_cluster_report() -> dict:
    """A minimal single-cluster DiscoveryReport."""
    report = _empty_report()
    report["candidates"] = [_candidate("note-a"), _candidate("note-b")]
    report["topic_clusters"] = [
        _cluster(
            "MOC01",
            title="Shell & Terminal (MOC)",
            confidence=0.78,
            candidate_stems=["note-a", "note-b"],
            slug="shell-terminal-moc",
        )
    ]
    report["parent_options_per_cluster"] = {
        "MOC01": [
            {
                "moc_stem": "2600 - Applied Sciences",
                "confidence": 0.85,
                "label": "Applied Sciences (Dewey 2600)",
            }
        ]
    }
    return report


# ── Tests ────────────────────────────────────────────────────────────────────


def test_dispatch_on_filename_pattern() -> None:
    """filename <YYYY-MM-DD>_<HHMM>_moc-proposal-<slug>.md routes to the MOC branch."""
    report = _single_cluster_report()
    filename, body = render_moc_proposal_doc(report, _Cfg())

    # Verify the filename matches the new dispatch pattern (canonical Tomo form)
    assert "_moc-proposal-" in filename and filename.endswith(".md"), (
        f"Unexpected filename: {filename!r}"
    )

    # Parse via the MOC branch using the generated body
    results = parse_moc_proposal_doc(body, filename=filename)

    # Should return a list (ConfirmedMOCProposal[])
    assert isinstance(results, list), f"Expected list, got {type(results)}"


def test_dispatch_on_frontmatter_type() -> None:
    """frontmatter type: tomo-proposal routes to MOC branch independent of filename."""
    report = _single_cluster_report()
    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # The body has `type: tomo-proposal` in frontmatter.
    # Call with a non-matching filename — dispatch must use frontmatter.
    results = parse_moc_proposal_doc(body, filename="some-other-name.md")

    assert isinstance(results, list), f"Expected list from frontmatter dispatch, got {type(results)}"


def test_skip_when_only_some_clusters_accepted() -> None:
    """Multi-cluster doc with 1 of 3 Accept ticked → returns exactly 1 ConfirmedMOCProposal."""
    report = _empty_report()
    report["candidates"] = [_candidate(f"note-{i}") for i in range(5)]
    report["topic_clusters"] = [
        _cluster("MOC01", title="Topic One (MOC)", confidence=0.80,
                 candidate_stems=["note-0", "note-1"], slug="topic-one-moc"),
        _cluster("MOC02", title="Topic Two (MOC)", confidence=0.65,
                 candidate_stems=["note-2", "note-3"], slug="topic-two-moc"),
        _cluster("MOC03", title="Topic Three (MOC)", confidence=0.50,
                 candidate_stems=["note-4"], slug="topic-three-moc"),
    ]
    report["parent_options_per_cluster"] = {}

    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Tick only the first Accept (MOC01 which is highest confidence, rendered first)
    # The rendered body has `- [ ] Accept` lines — tick only the first one
    first_accept_pos = body.index("- [ ] Accept")
    body_one_accepted = (
        body[:first_accept_pos]
        + "- [x] Accept"
        + body[first_accept_pos + len("- [ ] Accept"):]
    )

    results = parse_moc_proposal_doc(body_one_accepted, filename=_filename)

    assert len(results) == 1, (
        f"Expected 1 accepted proposal, got {len(results)}. "
        f"Results: {results}"
    )


def test_no_clusters_accepted_returns_empty() -> None:
    """No Accept ticks → returns [] (eligible for squelch)."""
    report = _single_cluster_report()
    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Do NOT tick any Accept — body has `- [ ] Accept` (unchecked)
    assert "- [ ] Accept" in body, "Fixture must contain unchecked Accept"
    assert "- [x] Accept" not in body, "Fixture must not have Accept ticked by default"

    results = parse_moc_proposal_doc(body, filename=_filename)

    assert results == [], (
        f"Expected empty list when no Accept ticked, got {results}"
    )


def test_parse_children_list_extracts_ticked_only() -> None:
    """Children section: only [x] items extracted, [ ] items ignored."""
    report = _empty_report()
    report["candidates"] = [
        _candidate("note-yes-1"),
        _candidate("note-yes-2"),
        _candidate("note-no-1"),
    ]
    report["topic_clusters"] = [
        _cluster(
            "MOC01",
            title="Children Test (MOC)",
            confidence=0.75,
            candidate_stems=["note-yes-1", "note-yes-2", "note-no-1"],
            slug="children-test-moc",
        )
    ]
    report["parent_options_per_cluster"] = {}

    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Tick Accept for the one cluster
    body_accepted = body.replace("- [ ] Accept", "- [x] Accept", 1)

    # Untick note-no-1 in Children
    body_modified = body_accepted.replace(
        "- [x] [[note-no-1]]", "- [ ] [[note-no-1]]"
    )

    results = parse_moc_proposal_doc(body_modified, filename=_filename)

    assert len(results) == 1
    children = results[0]["children"]
    assert "note-yes-1" in children, f"note-yes-1 missing from children: {children}"
    assert "note-yes-2" in children, f"note-yes-2 missing from children: {children}"
    assert "note-no-1" not in children, f"note-no-1 should NOT be in children: {children}"


def test_parse_parent_single_select_first_check_wins() -> None:
    """Multiple parent options; only the first checked one is used as parent."""
    report = _empty_report()
    report["candidates"] = [_candidate("note-a")]
    report["topic_clusters"] = [
        _cluster(
            "MOC01",
            title="Parent Test (MOC)",
            confidence=0.80,
            candidate_stems=["note-a"],
            slug="parent-test-moc",
        )
    ]
    # Two parent options — renderer ticks first one [x], second is [ ]
    report["parent_options_per_cluster"] = {
        "MOC01": [
            {"moc_stem": "First Parent", "confidence": 0.90, "label": "First Parent MOC"},
            {"moc_stem": "Second Parent", "confidence": 0.70, "label": "Second Parent MOC"},
        ]
    }

    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Tick Accept
    body_accepted = body.replace("- [ ] Accept", "- [x] Accept", 1)

    results = parse_moc_proposal_doc(body_accepted, filename=_filename)

    assert len(results) == 1
    # First option has [x] in rendered output → wins as parent
    assert results[0]["parent"] == "First Parent", (
        f"Expected 'First Parent' as parent, got {results[0].get('parent')!r}"
    )


def test_parse_override_toggle_extracts_bool() -> None:
    """Ticking 'Keep existing up::' → override_preserve_existing_up == True."""
    report = _single_cluster_report()
    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Accept the cluster
    body_accepted = body.replace("- [ ] Accept", "- [x] Accept", 1)

    # Tick the override checkbox
    body_override = body_accepted.replace(
        "- [ ] **Keep existing up::", "- [x] **Keep existing up::"
    )

    results = parse_moc_proposal_doc(body_override, filename=_filename)

    assert len(results) == 1
    assert results[0].get("override_preserve_existing_up") is True, (
        f"Expected override_preserve_existing_up=True, got "
        f"{results[0].get('override_preserve_existing_up')!r}"
    )


def test_parse_override_toggle_false_by_default() -> None:
    """Unchecked 'Bestehende up:: behalten' → override_preserve_existing_up == False."""
    report = _single_cluster_report()
    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Accept the cluster, do NOT tick the override
    body_accepted = body.replace("- [ ] Accept", "- [x] Accept", 1)

    results = parse_moc_proposal_doc(body_accepted, filename=_filename)

    assert len(results) == 1
    assert results[0].get("override_preserve_existing_up") is False, (
        f"Expected override_preserve_existing_up=False, got "
        f"{results[0].get('override_preserve_existing_up')!r}"
    )


def test_editable_text_fields_extracted() -> None:
    """Title, Location, and Template are extracted from inline **Field:** lines."""
    report = _empty_report()
    report["candidates"] = [_candidate("note-x")]
    report["topic_clusters"] = [
        _cluster(
            "MOC01",
            title="Field Extraction (MOC)",
            confidence=0.85,
            candidate_stems=["note-x"],
            location="Atlas/200 Maps/",
            template="t_moc_tomo",
            slug="field-extraction-moc",
        )
    ]
    report["parent_options_per_cluster"] = {}

    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Accept the cluster
    body_accepted = body.replace("- [ ] Accept", "- [x] Accept", 1)

    results = parse_moc_proposal_doc(body_accepted, filename=_filename)

    assert len(results) == 1
    item = results[0]

    assert item.get("title") == "Field Extraction (MOC)", (
        f"Expected title 'Field Extraction (MOC)', got {item.get('title')!r}"
    )
    assert item.get("location") is not None and "200 Maps" in item["location"], (
        f"Expected location containing '200 Maps', got {item.get('location')!r}"
    )
    assert item.get("template") == "t_moc_tomo", (
        f"Expected template 't_moc_tomo', got {item.get('template')!r}"
    )


# ── T5.1 tests — tomo.doc_type dispatch + ticked/unticked split ──────────────


def test_dispatch_classified_as_moc_proposal_via_tomo_doc_type() -> None:
    """tomo.doc_type=moc-proposal in frontmatter → classified as MOC branch.

    The fixture has tomo: block with doc_type=moc-proposal, state=pending-accept,
    but NO matching filename pattern. _is_moc_proposal_doc must use the tomo:
    block as the PRIMARY classifier (F-47 AC-5.1).
    """
    report = _single_cluster_report()
    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Verify: body has tomo: block (produced by T2.4)
    assert "doc_type: moc-proposal" in body, (
        f"Fixture must carry tomo.doc_type in frontmatter; body[:400]:\n{body[:400]}"
    )

    # Call with a non-matching filename — must still classify via tomo: block
    result = _is_moc_proposal_doc(body, filename="some-unrelated-name.md")
    assert result is True, (
        "Expected _is_moc_proposal_doc=True when tomo.doc_type=moc-proposal "
        "is present, even with non-matching filename"
    )


def test_enumerate_returns_only_ticked_clusters() -> None:
    """3 MOC blocks: MOC01 [x] Accept, MOC02 [ ] Accept, MOC03 [x] Accept.

    enumerate_moc_sections_split must return:
      ticked   = [MOC01, MOC03]
      unticked = [MOC02]
    """
    report = _empty_report()
    report["candidates"] = [_candidate(f"note-{i}") for i in range(4)]
    report["topic_clusters"] = [
        _cluster("MOC01", title="Ticked One (MOC)", confidence=0.80,
                 candidate_stems=["note-0", "note-1"], slug="ticked-one-moc"),
        _cluster("MOC02", title="Unticked Two (MOC)", confidence=0.65,
                 candidate_stems=["note-2"], slug="unticked-two-moc"),
        _cluster("MOC03", title="Ticked Three (MOC)", confidence=0.50,
                 candidate_stems=["note-3"], slug="ticked-three-moc"),
    ]
    report["parent_options_per_cluster"] = {}

    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Tick MOC01 and MOC03 (1st and 3rd occurrence of "- [ ] Accept")
    # The rendered body has clusters sorted by confidence DESC: MOC01 (0.80), MOC02 (0.65), MOC03 (0.50)
    # We need to tick the 1st and 3rd "- [ ] Accept"
    parts = body.split("- [ ] Accept")
    assert len(parts) == 4, f"Expected 3 clusters (4 parts after split), got {len(parts)}"
    # Rebuild: tick positions 0 and 2 (MOC01 and MOC03)
    body_modified = (
        parts[0] + "- [x] Accept" +
        parts[1] + "- [ ] Accept" +
        parts[2] + "- [x] Accept" +
        parts[3]
    )

    ticked, unticked = enumerate_moc_sections_split(body_modified)

    ticked_ids = [c["moc_id"] for c in ticked]
    unticked_ids = [c["moc_id"] for c in unticked]

    assert len(ticked) == 2, f"Expected 2 ticked clusters, got {len(ticked)}: {ticked_ids}"
    assert len(unticked) == 1, f"Expected 1 unticked cluster, got {len(unticked)}: {unticked_ids}"
    assert "MOC01" in ticked_ids, f"MOC01 should be ticked; ticked={ticked_ids}"
    assert "MOC03" in ticked_ids, f"MOC03 should be ticked; ticked={ticked_ids}"
    assert "MOC02" in unticked_ids, f"MOC02 should be unticked; unticked={unticked_ids}"


def test_child_wikilinks_extracted_per_cluster() -> None:
    """Ticked cluster dict has 'children' key with all child wikilinks extracted."""
    report = _empty_report()
    report["candidates"] = [_candidate(f"child-{i}") for i in range(5)]
    report["topic_clusters"] = [
        _cluster(
            "MOC01",
            title="Children Extraction (MOC)",
            confidence=0.75,
            candidate_stems=[f"child-{i}" for i in range(5)],
            slug="children-extraction-moc",
        )
    ]
    report["parent_options_per_cluster"] = {}

    _filename, body = render_moc_proposal_doc(report, _Cfg())

    # Tick the single Accept
    body_accepted = body.replace("- [ ] Accept", "- [x] Accept", 1)

    ticked, _unticked = enumerate_moc_sections_split(body_accepted)

    assert len(ticked) == 1, f"Expected 1 ticked cluster, got {len(ticked)}"
    cluster = ticked[0]

    assert "children" in cluster, f"Cluster dict must have 'children' key: {cluster.keys()}"
    children = cluster["children"]
    assert isinstance(children, list), f"children must be list, got {type(children)}"
    assert len(children) == 5, (
        f"Expected 5 children wikilinks, got {len(children)}: {children}"
    )
    # Each entry is the wikilink stem (not full [[...]] syntax)
    for i in range(5):
        assert f"child-{i}" in children, (
            f"Expected child-{i} in children list: {children}"
        )


def test_unticked_clusters_returned_separately_for_squelch() -> None:
    """Unticked clusters each carry a 'topic_signature' key for squelch persistence."""
    report = _empty_report()
    report["candidates"] = [_candidate(f"note-{i}") for i in range(3)]
    report["topic_clusters"] = [
        _cluster("MOC01", title="Squelch Alpha (MOC)", confidence=0.70,
                 candidate_stems=["note-0", "note-1"],
                 topic_keywords=["alpha", "topic"],
                 slug="squelch-alpha-moc"),
        _cluster("MOC02", title="Squelch Beta (MOC)", confidence=0.60,
                 candidate_stems=["note-2"],
                 topic_keywords=["beta"],
                 slug="squelch-beta-moc"),
    ]
    report["parent_options_per_cluster"] = {}

    _filename, body = render_moc_proposal_doc(report, _Cfg())
    # Leave all clusters un-ticked (no Accept box checked)

    ticked, unticked = enumerate_moc_sections_split(body)

    assert len(ticked) == 0, f"Expected 0 ticked, got {len(ticked)}"
    assert len(unticked) == 2, f"Expected 2 unticked, got {len(unticked)}"

    for cluster in unticked:
        assert "topic_signature" in cluster, (
            f"Unticked cluster must carry topic_signature for squelch: {cluster.keys()}"
        )
        sig = cluster["topic_signature"]
        assert isinstance(sig, str) and len(sig) > 0, (
            f"topic_signature must be a non-empty string, got {sig!r}"
        )


def test_filename_heuristic_fallback_still_works() -> None:
    """Backward-compat: no tomo: block, but filename matches tomo-moc-proposal-*.

    _is_moc_proposal_doc must still return True via the filename heuristic,
    even when the document has no tomo: block (old F-43 vault docs).
    """
    # Minimal body WITHOUT a tomo: block, but with MOC structure
    body_no_tomo_block = """\
---
type: tomo-proposal
proposal_kind: moc
created: 2026-01-01 00:00
status: pending
---

# MOC Proposal

### MOC01 — Legacy Topic (MOC)

- [ ] Accept
"""
    # Filename matches the old pattern
    result = _is_moc_proposal_doc(body_no_tomo_block, filename="tomo-moc-proposal-20260101-1200-legacy.md")
    assert result is True, (
        "Expected _is_moc_proposal_doc=True for filename-pattern match, "
        "even without tomo: block in frontmatter"
    )
