#!/usr/bin/env python3
# version: 0.1.0
"""test_vault_explorer_step9_scanner.py — Contract test for vault-explorer.md Step 9
orchestration changes (spec 015, T4.2 / F-34 Condition B).

vault-explorer.md is an LLM-loaded runtime agent spec (not a Python module).
These tests validate the Step 9 region of the spec text contains every imperative
required by SDD §Error Handling and the Deployment View:

  (a) atomic-note-indexer.py is invoked in Step 9.
  (b) atomic-note-indexer.py appears BEFORE cache-builder.py in Step 9.
  (c) cache-builder.py is called with --accumulation.
  (d) Graceful-degrade language exists: scanner failure → run cache-builder WITHOUT
      --accumulation (empty index, not an abort).
  (e) The existing STRICT cache rule ("cache MUST be generated by cache-builder.py")
      is still present.
  (f) No 2>&1 redirect into a JSON-captured file (memory: feedback_never_redirect_stderr_into_json).
  (g) # version: was bumped above 0.11.4 (the pre-T4.2 value).

Assertions use substring/offset checks against an isolated Step 9 region so each
assertion FAILS if the corresponding imperative line is removed (no vacuous ORs).
"""
from __future__ import annotations

import re
from pathlib import Path

TESTS_DIR = Path(__file__).resolve().parent
REPO_ROOT = TESTS_DIR.parent
AGENT_PATH = REPO_ROOT / "tomo" / "dot_claude" / "agents" / "vault-explorer.md"

# Step 9 heading and the heading that follows it (Step 10) to bound the region.
STEP9_HEADING = "### Step 9"
STEP10_HEADING = "### Step 10"

PRE_TASK_VERSION = (0, 11, 4)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _agent_text() -> str:
    assert AGENT_PATH.exists(), f"Agent file not found: {AGENT_PATH}"
    return AGENT_PATH.read_text()


def _step9_region(text: str) -> str:
    """Return only the text between '### Step 9' and '### Step 10' headings."""
    start = text.find(STEP9_HEADING)
    assert start != -1, f"{STEP9_HEADING!r} not found in vault-explorer.md"
    end = text.find(STEP10_HEADING, start)
    assert end != -1, f"{STEP10_HEADING!r} not found after Step 9 start"
    region = text[start:end]
    assert len(region) > 100, (
        f"Step 9 region is suspiciously short ({len(region)} chars) — "
        "check STEP9_HEADING / STEP10_HEADING markers"
    )
    return region


# ---------------------------------------------------------------------------
# (a) atomic-note-indexer.py is invoked in Step 9
# ---------------------------------------------------------------------------

def test_step9_invokes_atomic_note_indexer():
    """Step 9 must call atomic-note-indexer.py."""
    text = _agent_text()
    region = _step9_region(text)
    assert "atomic-note-indexer.py" in region, (
        "Step 9 region must contain an invocation of atomic-note-indexer.py"
    )


# ---------------------------------------------------------------------------
# (b) atomic-note-indexer.py appears BEFORE cache-builder.py in Step 9
# ---------------------------------------------------------------------------

def test_step9_indexer_before_cache_builder():
    """atomic-note-indexer.py must appear before cache-builder.py in Step 9."""
    text = _agent_text()
    region = _step9_region(text)

    indexer_pos = region.find("atomic-note-indexer.py")
    builder_pos = region.find("cache-builder.py")

    assert indexer_pos != -1, "atomic-note-indexer.py not found in Step 9 region"
    assert builder_pos != -1, "cache-builder.py not found in Step 9 region"
    assert indexer_pos < builder_pos, (
        "atomic-note-indexer.py must appear BEFORE cache-builder.py in Step 9 "
        f"(indexer at offset {indexer_pos}, builder at offset {builder_pos})"
    )


# ---------------------------------------------------------------------------
# (c) cache-builder.py is passed --accumulation in Step 9
# ---------------------------------------------------------------------------

def test_step9_cache_builder_receives_accumulation_flag():
    """cache-builder.py in Step 9 must be invoked with --accumulation."""
    text = _agent_text()
    region = _step9_region(text)

    # Find the first cache-builder call and look for --accumulation within the same
    # bash code block (up to 400 chars after cache-builder.py).
    builder_pos = region.find("cache-builder.py")
    assert builder_pos != -1, "cache-builder.py not found in Step 9 region"

    window = region[builder_pos: builder_pos + 400]
    assert "--accumulation" in window, (
        "cache-builder.py invocation in Step 9 must include --accumulation flag. "
        f"Window after cache-builder.py: {window!r}"
    )


# ---------------------------------------------------------------------------
# (d) Graceful-degrade: scanner failure → cache-builder runs WITHOUT --accumulation
# ---------------------------------------------------------------------------

def test_step9_graceful_degrade_scanner_failure_runs_without_accumulation():
    """Step 9 must document graceful degradation: scanner failure → cache-builder runs
    WITHOUT --accumulation (empty index, not an abort)."""
    text = _agent_text()
    region = _step9_region(text)

    # We need BOTH conditions to hold within the region:
    # 1. Some failure/error language for the scanner.
    # 2. Language that cache-builder still runs without --accumulation.
    #
    # "without --accumulation" OR "without accumulation" (case-insensitive) captures the
    # intent precisely; this phrase must be present to document the fallback path.
    has_failure_language = (
        "scanner fails" in region.lower()
        or "indexer fails" in region.lower()
    )
    # Normalise for matching: strip backticks and collapse newlines to spaces so that
    # line-wrapped prose like "WITHOUT\n`--accumulation`" matches "without --accumulation".
    region_plain = region.replace("`", "").replace("\n", " ")
    has_no_accumulation_fallback = (
        "without --accumulation" in region_plain.lower()
        or "without accumulation" in region_plain.lower()
    )

    assert has_failure_language, (
        "Step 9 region must contain failure/error language for the scanner "
        "(e.g. 'scanner fails', 'if the scanner', 'indexer fails')"
    )
    assert has_no_accumulation_fallback, (
        "Step 9 region must specify that cache-builder runs WITHOUT --accumulation "
        "when the scanner fails (graceful degrade per SDD §Error Handling). "
        f"Step 9 region: {region!r}"
    )


# ---------------------------------------------------------------------------
# (e) STRICT cache rule is preserved
# ---------------------------------------------------------------------------

def test_step9_strict_cache_rule_preserved():
    """The existing STRICT rule that cache MUST be generated by cache-builder.py must survive."""
    text = _agent_text()
    region = _step9_region(text)

    # Both STRICT marker and "cache-builder.py" must appear in the rule.
    has_strict = "STRICT" in region
    has_cache_builder_ref = "cache-builder.py" in region

    assert has_strict, (
        "Step 9 STRICT block must be preserved — "
        "cache MUST be generated by cache-builder.py, not written by hand"
    )
    assert has_cache_builder_ref, (
        "Step 9 region must still reference cache-builder.py in the STRICT rule"
    )

    # The STRICT block must reference cache-builder within 300 chars of "STRICT".
    strict_pos = region.find("STRICT")
    builder_in_strict_window = "cache-builder.py" in region[strict_pos: strict_pos + 300]
    assert builder_in_strict_window, (
        "The STRICT block must reference cache-builder.py within its text (within 300 chars)"
    )


# ---------------------------------------------------------------------------
# (f) No 2>&1 redirect into a JSON-captured file
# ---------------------------------------------------------------------------

def test_step9_no_stderr_redirect_into_json_capture():
    """Step 9 must NOT merge stderr into the stdout-captured JSON file (2>&1 on scanner line)."""
    text = _agent_text()
    region = _step9_region(text)

    # Find all lines that redirect stdout to a .json file
    # The dangerous pattern is: > "file.json" 2>&1  or  2>&1 > "file.json"
    json_redirect_lines = [
        line for line in region.splitlines()
        if re.search(r'>\s*["\']?[^"\']*\.json["\']?', line)
    ]

    for line in json_redirect_lines:
        assert "2>&1" not in line, (
            f"Step 9 must not redirect stderr into a JSON-captured file. "
            f"Found: {line!r}"
        )


# ---------------------------------------------------------------------------
# (g) # version: was bumped above 0.11.4
# ---------------------------------------------------------------------------

def test_vault_explorer_version_bumped():
    """vault-explorer.md version must be greater than 0.11.4 (pre-T4.2 value)."""
    text = _agent_text()
    match = re.search(r"#\s*version:\s*(\d+)\.(\d+)\.(\d+)", text)
    assert match, "vault-explorer.md must have a '# version: X.Y.Z' comment"
    major, minor, patch = int(match.group(1)), int(match.group(2)), int(match.group(3))
    version_tuple = (major, minor, patch)
    assert version_tuple > PRE_TASK_VERSION, (
        f"vault-explorer.md version {major}.{minor}.{patch} must be > "
        f"{PRE_TASK_VERSION[0]}.{PRE_TASK_VERSION[1]}.{PRE_TASK_VERSION[2]} "
        "(T4.2 version bump required)"
    )


def test_vault_explorer_version_no_parenthetical():
    """Version comment must be number-only — no parenthetical after the version number."""
    text = _agent_text()
    for line in text.splitlines():
        if "version:" in line and re.search(r"#\s*version:", line):
            assert "(" not in line, (
                f"Version comment must be number-only, no parenthetical. Found: {line!r}"
            )
