#!/usr/bin/env python3
# version: 0.1.0
"""conftest.py — Shared pytest fixtures for F-43 T6.1 producer-side integration tests.

All fixtures are scoped to `tmp_path` (per-test isolation).
No fixture mutates the real Privat-Test directory or tomo-instance.

See README.md for environment invariants and scope decisions.
"""
from __future__ import annotations

import importlib.util
import json
import shutil
import sys
from pathlib import Path

import pytest
import yaml

# ── Repo paths ────────────────────────────────────────────────────────────────

TESTS_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = TESTS_DIR.parent
SCRIPTS_DIR = REPO_ROOT / "tomo" / "scripts"

PRIVAT_TEST_ROOT = Path("/Volumes/Moon/Coding/MiYo/temp/Privat-Test")

# ── Script loaders ────────────────────────────────────────────────────────────

sys.path.insert(0, str(SCRIPTS_DIR))


def _load_module(name: str, path: Path):
    """Load a Python file with hyphens in its name as a module."""
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


# Pre-load the scripts we exercise so the tests can call their functions directly.
moc_discovery_mod = _load_module("moc_discovery", SCRIPTS_DIR / "moc-discovery.py")
suggestions_reducer_mod = _load_module(
    "suggestions_reducer", SCRIPTS_DIR / "suggestions-reducer.py"
)
suggestion_parser_mod = _load_module(
    "suggestion_parser", SCRIPTS_DIR / "suggestion-parser.py"
)
instruction_render_mod = _load_module(
    "instruction_render", SCRIPTS_DIR / "instruction-render.py"
)

# ── Helper: minimal discovery-cache.yaml -────────────────────────────────────

# A minimal cache covering the Dataview cluster in Privat-Test's
# Atlas/202 Notes/2611 Code Snippets/ directory.  The integration tests clone a
# slice of Privat-Test for filesystem assertions but seed the cache independently
# (it's generated by /explore-vault in production; here we provide a hand-crafted
# seed so tests are deterministic and not Kado-dependent).

_DATAVIEW_NOTES = [
    "Dataview - Contains Explained",
    "Dataview - Dateformat",
    "Dataview - Display Inlinks",
    "Dataview - Display notes which have inline field",
    "Dataview - Display or Embedded Sections",
    "Dataview - Dynamic Queries via Variable",
    "Dataview - Exclude specific note",
    "Dataview - Filename contains certain text",
    "Dataview - Important Dangling Notes",
    "Dataview - Notes in specific timeframe",
]

_CONCEPTS_MOC = [
    "Concepts (MOC)",
    "FlowCreation (MOC)",
    "Frameworks (MOC)",
    "Habits (MOC)",
    "Idea Emergence (MOC)",
]


def _seed_discovery_cache(tmp_path: Path) -> Path:
    """Write a minimal discovery-cache.yaml covering several test clusters.

    Returns the path to the written file.

    Clusters covered:
    - Dataview cluster (tag:Obsidian/Plugin/Dataview, folder:Atlas/202 Notes/2611 Code Snippets/)
    - PKM cluster (free-text "map of content")
    - Class cluster (class:2600 → 2611 Code Snippets)
    """
    map_notes = [
        {
            "path": f"Atlas/200 Maps/{stem}.md",
            "title": stem,
            "discovered_via": "tag",
            "level": 1,
            "parent_moc": None,
            "child_mocs": [],
            "sibling_mocs": [],
            "state": None,
            "topics": ["obsidian", "plugin", "dataview", "tool"],
            "sections": [],
            "linked_notes": 2,
            "classification": "2600",
        }
        for stem in _CONCEPTS_MOC
    ] + [
        {
            "path": "Atlas/200 Maps/2600 - Applied Sciences.md",
            "title": "2600 - Applied Sciences",
            "discovered_via": "tag",
            "level": 0,
            "parent_moc": None,
            "child_mocs": [],
            "sibling_mocs": [],
            "state": None,
            "topics": ["applied sciences", "code", "dataview", "obsidian"],
            "sections": [],
            "linked_notes": 10,
            "classification": "2600",
        }
    ]

    # Atomic notes — Dataview cluster
    atomic_notes = [
        {
            "path": f"Atlas/202 Notes/2611 Code Snippets/{stem}.md",
            "title": stem,
            "tags": ["Obsidian/Plugin/Dataview"],
            "topics": ["dataview", "obsidian", "plugin", "query"],
            "classification": "2611",
        }
        for stem in _DATAVIEW_NOTES
    ] + [
        # PKM cluster notes (free-text / title mode)
        {
            "path": f"Atlas/202 Notes/{stem}.md",
            "title": stem,
            "tags": ["type/note/normal"],
            "topics": ["map of content", "moc", "pkm", "linking"],
            "classification": None,
        }
        for stem in ["Map of Content", "Map vs MOC", "Mapmaking", "Higher Order Notes", "Concepts"]
    ]

    # spec 021 T2.1: moc-discovery reads the MOC-structure cache via the loader,
    # which projects entries[kind=="moc"] → map_notes (shim). To preserve the
    # exact pre-wiring map_notes content these e2e tests were written against
    # (title/free-text read map_notes[].topics; Phase 6 dedups against it), the
    # whole pre-existing combined set (map_notes + atomic_notes) is written as
    # kind:moc entries so the shim surfaces it unchanged. A recent last_scan keeps
    # the cache FRESH so the loader loads it without a (Kado-needing) rebuild.
    from datetime import datetime, timezone

    fresh = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    entries = (
        [{**m, "kind": "moc"} for m in map_notes]
        + [{**a, "kind": "moc"} for a in atomic_notes]
    )
    cache = {
        "moc_cache_version": 1,
        "last_scan": fresh,
        "ttl_days": 1,
        "scope_paths": ["Atlas/200 Maps/", "Atlas/202 Notes/"],
        "exclude_paths": [],
        "moc_tag": "type/others/moc",
        "entries": entries,
        "placeholder_mocs": [],
    }

    cache_path = tmp_path / "moc-structure-cache.yaml"
    cache_path.write_text(yaml.dump(cache, allow_unicode=True), encoding="utf-8")
    return cache_path


# ── Helper: minimal vault-config.yaml ────────────────────────────────────────


def _seed_vault_config(tmp_path: Path, vault_root: Path) -> Path:
    """Write a minimal vault-config.yaml for test runs.

    Returns the path to the written file.
    """
    config = {
        "profile": "miyo",
        "concepts": {
            "inbox": str(vault_root / "100 Inbox") + "/",
            "atomic_note": {"path": "Atlas/202 Notes/"},
            "map_note": {"path": "Atlas/200 Maps/"},
        },
        "tomo": {
            "moc_proposal": {
                "min_notes": 3,
                "confidence_threshold": 0.10,
                "max_results": 5,
                "candidate_cap": 200,
                "cache_miss_max_batches": 5,
                "squelch_runs": 3,
            }
        },
        "profile_data": {
            "miyo": {
                "title_suffix": " (MOC)",
                "moc_path": "Atlas/200 Maps/",
            }
        },
    }
    config_path = tmp_path / "vault-config.yaml"
    config_path.write_text(yaml.dump(config, allow_unicode=True), encoding="utf-8")
    return config_path


# ── Fixtures ──────────────────────────────────────────────────────────────────


@pytest.fixture()
def privat_test_clone(tmp_path: Path) -> Path:
    """Clone a small, test-relevant slice of Privat-Test into tmp_path.

    Clones:
    - Atlas/200 Maps/         — existing MOC files (for collision guard test)
    - Atlas/202 Notes/2611 Code Snippets/   — Dataview cluster (tag/folder/class mode)
    - Atlas/202 Notes/ (direct notes)  — PKM cluster (free-text/title mode)
    - 100 Inbox/              — empty inbox dir

    NEVER mutates the real Privat-Test directory.
    """
    src = PRIVAT_TEST_ROOT
    dst = tmp_path / "vault"

    # Clone Atlas/200 Maps
    maps_src = src / "Atlas" / "200 Maps"
    maps_dst = dst / "Atlas" / "200 Maps"
    if maps_src.exists():
        shutil.copytree(maps_src, maps_dst)
    else:
        maps_dst.mkdir(parents=True, exist_ok=True)

    # Clone Atlas/202 Notes/2611 Code Snippets (Dataview cluster)
    snippets_src = src / "Atlas" / "202 Notes" / "2611 Code Snippets"
    snippets_dst = dst / "Atlas" / "202 Notes" / "2611 Code Snippets"
    if snippets_src.exists():
        shutil.copytree(snippets_src, snippets_dst)
    else:
        snippets_dst.mkdir(parents=True, exist_ok=True)

    # Clone direct Atlas/202 Notes/ notes (PKM cluster)
    notes_src = src / "Atlas" / "202 Notes"
    notes_dst = dst / "Atlas" / "202 Notes"
    notes_dst.mkdir(parents=True, exist_ok=True)
    pkm_stems = [
        "Map of Content.md",
        "Map vs MOC.md",
        "Mapmaking.md",
        "Higher Order Notes.md",
        "Concepts.md",
    ]
    for stem in pkm_stems:
        f = notes_src / stem
        if f.exists():
            shutil.copy2(f, notes_dst / stem)

    # Empty inbox
    inbox_dst = dst / "100 Inbox"
    inbox_dst.mkdir(parents=True, exist_ok=True)

    return dst


@pytest.fixture()
def seeded_discovery_cache(tmp_path: Path) -> Path:
    """Write a discovery-cache.yaml covering tag/folder/class/title/freetext clusters.

    Returns path to the cache file. Does NOT require Kado or a live vault.
    """
    return _seed_discovery_cache(tmp_path)


@pytest.fixture()
def isolated_tomo_state(tmp_path: Path) -> dict[str, Path]:
    """Create a fresh tomo state directory with an empty squelch registry.

    Returns a dict with keys:
      - 'state_dir'     : Path to the state/ directory
      - 'squelch_path'  : Path to moc-squelch.json (empty registry)
      - 'tomo_tmp_dir'  : Path to tomo-tmp/ directory
    """
    state_dir = tmp_path / "state"
    state_dir.mkdir(parents=True, exist_ok=True)

    squelch_path = state_dir / "moc-squelch.json"
    squelch_path.write_text(
        json.dumps({"schema_version": "1", "last_run_id": "", "rejections": []}, indent=2),
        encoding="utf-8",
    )

    tomo_tmp = tmp_path / "tomo-tmp"
    tomo_tmp.mkdir(parents=True, exist_ok=True)

    return {
        "state_dir": state_dir,
        "squelch_path": squelch_path,
        "tomo_tmp_dir": tomo_tmp,
    }


# ── Report / cluster builder helpers ─────────────────────────────────────────

def make_candidate(
    stem: str,
    *,
    existing_up: str | None = None,
    existing_up_broken: bool = False,
    topics: list[str] | None = None,
    classification: str | None = None,
    folder: str = "Atlas/202 Notes/2611 Code Snippets/",
) -> dict:
    return {
        "stem": stem,
        "path": f"{folder}{stem}.md",
        "topics": topics or ["dataview", "obsidian", "plugin"],
        "existing_up": existing_up,
        "existing_up_broken": existing_up_broken,
        "classification": classification,
        "level": 0,
    }


def make_cluster(
    cluster_id: str,
    *,
    title: str,
    confidence: float,
    candidate_stems: list[str],
    topic_keywords: list[str] | None = None,
    slug: str | None = None,
    location: str = "Atlas/200 Maps/",
    template: str = "t_moc_tomo",
    existing_up: list[dict] | None = None,
    parent_options: list[dict] | None = None,
) -> tuple[dict, list[dict]]:
    """Return (cluster_dict, parent_options_list)."""
    cluster = {
        "cluster_id": cluster_id,
        "title": title,
        "confidence": confidence,
        "candidate_stems": candidate_stems,
        "topic_keywords": topic_keywords or ["dataview", "obsidian"],
        "slug": slug or title.lower().replace(" ", "-").replace("(", "").replace(")", ""),
        "location": location,
        "template": template,
        "existing_up": existing_up or [],
    }
    parents = parent_options or [
        {
            "moc_stem": "2600 - Applied Sciences",
            "confidence": 0.85,
            "label": "Applied Sciences (Dewey 2600)",
        }
    ]
    return cluster, parents


def make_discovery_report(
    clusters: list[dict],
    parent_options: dict[str, list[dict]],
    *,
    mode: str = "tag",
    trigger_arg: str = "Obsidian/Plugin/Dataview",
    candidates: list[dict] | None = None,
) -> dict:
    """Build a minimal DiscoveryReport dict for use as a reducer input."""
    return {
        "schema_version": "1",
        "run_id": "integration-test-run",
        "mode": mode,
        "trigger_arg": trigger_arg,
        "profile": "miyo",
        "candidates_total": len(candidates or []),
        "candidates_after_prefilter": len(candidates or []),
        "candidates_capped": False,
        "candidates": candidates or [],
        "topic_clusters": clusters,
        "parent_options_per_cluster": parent_options,
        "duplicates_skipped": [],
        "squelched": [],
        "abort_reason": None,
        "abort_message": None,
        "extracted_via_llm_count": 0,
        "cache_miss_batches_used": 0,
    }
